-- ============================================================================
-- change_log_suppression.sql
-- ============================================================================
--
-- 回放抑制回显模式（Echo Suppression for Replay）
--
-- 问题场景：
--   云同步回放远端变更时，INSERT / UPDATE / DELETE 语句会触发
--   __change_log 触发器，产生"回显条目"（echo entries），
--   这些条目在下一次同步时会被误判为新的本地变更。
--
-- 解决方案：
--   sync::apply_downloaded_changes 在单个事务内执行回放，
--   在每条变更前后使用以下模式：
--
--   1. 回放前记录 __change_log 当前最大 id：
--      SELECT COALESCE(MAX(id), 0) FROM __change_log
--
--   2. 执行变更（INSERT / UPDATE / DELETE / UPSERT）
--
--   3. 回放后标记新产生的 __change_log 条目为已同步：
--      UPDATE __change_log
--      SET sync_version = ?1
--      WHERE id > ?2
--        AND sync_version = 0
--        AND table_name = ?3
--        AND record_id = ?4
--
-- 注意事项：
--   - 整个回放过程在一个事务内，用户无法并发写入
--   - 只标记当前 table + record 的新条目，不影响其他表的真实变更
--   - sync_version 设置为当前 Unix 时间戳，表示已被同步
--   - 此模式**不限制 operation**，因为 UPSERT 触发的独立 UPDATE
--     产生的 `operation = UPDATE` 条目也需被抑制
--
-- 使用示例（伪代码，实际实现在 Rust 的 apply_downloaded_changes）：
--
--   BEGIN IMMEDIATE;
--   PRAGMA defer_foreign_keys = ON;
--
--   -- 对每条远端变更循环
--   pre_log_max = SELECT COALESCE(MAX(id), 0) FROM __change_log;
--   -- 执行 INSERT/UPDATE/DELETE/UPSERT
--   UPDATE __change_log SET sync_version = <now_ts>
--     WHERE id > <pre_log_max> AND sync_version = 0
--     AND table_name = <tbl> AND record_id = <rid>;
--
--   -- 事务提交前校验外键约束
--   COMMIT;
--
-- 设计原则：
--   - 触发器保持简单（只记录变更），不内置回显抑制逻辑
--   - 抑制逻辑集中在应用层（Rust），保证可测试性和可控性
--   - 通过 sync_version 而非 DELETE 清理，保留审计线索
-- ============================================================================
